name: phpunit

on: [ push, pull_request ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.4 ]

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, fileinfo
          coverage: none

      - name: Setup sphinxsearch
        # sudo echo "START=yes\n" > /etc/default/sphinxsearch
        # sudo searchd --status
        run: |
          sudo cp sphinx.conf.ci /etc/sphinxsearch/sphinx.conf
          sudo sed -i 's/START=no/START=yes/g' /etc/default/sphinxsearch

      - name: Create database
        run: |
          sudo systemctl start mysql.service
          mysql -u root -proot -e 'CREATE DATABASE IF NOT EXISTS tests;'

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist
        env:
          # {"http-basic":{"example.com":{"username":"login","password":"key"}}}
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      - name: Install graphicsmagick
        run: sudo apt-get install graphicsmagick

      - name: Start sphinxsearch
        run: |
          cat /usr/share/doc/sphinxsearch/README.Debian
          sudo service sphinxsearch start
          cat /etc/default/sphinxsearch
          cat /etc/init.d/sphinxsearch
          sudo systemctl status sphinxsearch.service

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
          composer fresh

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
